# Generated by Django 3.0.3 on 2020-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecount',
            name='like_num',
        ),
        migrations.AddField(
            model_name='likecount',
            name='liked_num',
            field=models.IntegerField(default=0),
        ),
    ]
